# Generated by Django 5.2.2 on 2025-06-06 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0002_alter_persona_apellido_alter_persona_edad_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='apellido',
            new_name='apellidos',
        ),
        migrations.RenameField(
            model_name='persona',
            old_name='nombre',
            new_name='nombres',
        ),
        migrations.AddField(
            model_name='persona',
            name='donador',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='edad',
            field=models.IntegerField(),
        ),
    ]
